In [5]:
from dataset import *

x = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
y = torch.tensor([[-1,-1],[-4,-4],[-7,-7],[-10,-10],[-13,-13]])
print(x)
print(y)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
tensor([[ -1,  -1],
        [ -4,  -4],
        [ -7,  -7],
        [-10, -10],
        [-13, -13]])


In [17]:
(X1, X2), (y1,y2) = split_data(*shuffle_data(x,y),0.7)
print(X1)
print(X2)
print(y1)
print(y2)


tensor([[4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.]])
tensor([[10., 11., 12.],
        [13., 14., 15.]])
tensor([[-4., -4.],
        [-7., -7.],
        [-1., -1.]])
tensor([[-10., -10.],
        [-13., -13.]])
